language: python
python:
  - "2.7"
  - "3.4"
  - "2.6"
  - "3.3"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - "pip install --use-mirrors -e ."
    - "pip install coverage coveralls"
script:
    - "python ./setup.py nosetests"
after_success:
    - coveralls
